### ISSUE TITLE
File interceptor loads in bytes

### ISSUE THREAD

**Issue by ammarbrohi** [akashkrishnan98/Novice-script-kiddie-kit#1]
While executing your program my http website returns loads in form of bytes this  the condition

"exe" in request.load fails

What's the way around or what testing website you used that returns loads in plain text?

Thanks,

**Comment by akashkrishnan98** [comment]
I have replied to your mail Ammar, check it out.
I have also updated the code to work with HTTPS and fixed a few bugs along the way.
